-- Converted insert statements to latest schema
SET FOREIGN_KEY_CHECKS=0;

INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('A', '犬Aカテゴリ', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('G', '犬Gカテゴリ', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('C', '犬Cカテゴリ', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('D', '犬Dカテゴリ', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('B', '犬Bカテゴリ', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('E', '犬Eカテゴリ', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('F', '犬Fカテゴリ', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_CATEGORY_MASTER(category_code, category_name, sort_order, created_at, updated_at) VALUES ('CAT', '猫カテゴリ', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00001', 'DOG', 'トイ・プードル', 'A', 173642, 22.5, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00002', 'DOG', 'チワワ', 'A', 117865, 15.3, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00003', 'DOG', '混血犬（体重10kg未満）', 'A', 94943, 12.3, '(H) その他（特殊体型・MIX 等）', 'H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00004', 'DOG', '柴', 'G', 60145, 7.8, '(G) スピッツ・日本犬系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00005', 'DOG', 'ミニチュア・ダックスフンド', 'C', 59018, 7.7, '(C) 胴長短足系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00006', 'DOG', 'ポメラニアン', 'G', 32833, 4.3, '(G) スピッツ・日本犬系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00007', 'DOG', 'ミニチュア・シュナウザー', 'D', 23942, 3.1, '(D) テリア系・小～中型の活発犬', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00008', 'DOG', 'ヨークシャー・テリア', 'A', 20051, 2.6, '(A) 超小型～小型の愛玩系/(D) テリア系・小～中型の活発犬', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00009', 'DOG', 'フレンチ・ブルドッグ', 'B', 14295, 1.9, '(B) 短頭種', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00010', 'DOG', 'マルチーズ', 'A', 13968, 1.8, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00011', 'DOG', 'シー・ズー', 'A', 13703, 1.8, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00012', 'DOG', 'カニーンヘン・ダックスフンド', 'C', 13478, 1.7, '(C) 胴長短足系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00013', 'DOG', 'パピヨン', 'A', 10322, 1.3, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00014', 'DOG', 'ゴールデン・レトリーバー', 'E', 9338, 1.2, '(E) レトリーバー系（大型の鳥猟犬）', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00015', 'DOG', 'ウェルシュ・コーギー・ペンブローク', 'C', 8934, 1.2, '(C) 胴長短足系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00016', 'DOG', 'ジャック・ラッセル・テリア', 'D', 8134, 1.1, '(D) テリア系・小～中型の活発犬', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00017', 'DOG', 'ラブラドール・レトリーバー', 'E', 7465, 1, '(E) レトリーバー系（大型の鳥猟犬）', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00018', 'DOG', 'パグ', 'B', 7458, 1, '(B) 短頭種', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00019', 'DOG', 'キャバリア・キング・チャールズ・スパニエル', 'A', 6390, 0.8, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00020', 'DOG', 'ミニチュア・ピンシャー', 'A', 5999, 0.8, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00021', 'DOG', '混血犬（体重10kg以上20kg未満）', 'E', 5723, 0.7, '(E) その他（特殊体型・MIX 等）', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00022', 'DOG', 'ペキニーズ', 'B', 5439, 0.7, '(B) 短頭種', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00023', 'DOG', 'イタリアン・グレーハウンド', 'E', 5106, 0.7, '(H) その他（特殊体型・MIX 等）', 'H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00024', 'DOG', 'ボーダー・コーリー', 'F', 4963, 0.6, '(F) 牧羊・牧畜系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00025', 'DOG', 'ビーグル', 'A', 4892, 0.6, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00026', 'DOG', 'ビション・フリーゼ', 'A', 4396, 0.6, '(A) 超小型～小型の愛玩系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00027', 'DOG', 'シェットランド・シープドッグ', 'F', 4125, 0.5, '(F) 牧羊・牧畜系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00028', 'DOG', 'ボストン・テリア', 'B', 4088, 0.5, '(B) 短頭種', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00029', 'DOG', 'アメリカン・コッカー・スパニエル', 'E', 3064, 0.4, '(H) その他（特殊体型・MIX 等）', 'H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00030', 'DOG', '日本スピッツ', 'G', 1830, 0.2, '(G) スピッツ・日本犬系', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO RORO_BREED_MASTER(BREEDM_ID, pet_type, breed_name, category_code, population, population_rate, category_description, old_category, created_at, updated_at) VALUES ('PETM_00031', 'CAT', '猫', 'CAT' , NULL, NULL, 'Category_CAT', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



SET FOREIGN_KEY_CHECKS=1;
